!function(api) {
  function expect(actual, correct) {
    if (actual !== correct) throw new Error(actual + ' should be ' + correct)
  }

  expect(api.split, api.parse)
  expect(api.split('').length, 0)
  expect(api.split(' ').length, 0)
  expect(api.split('yes').join('-'), 'yes')
  expect(api.split('yes no').join('-'), 'yes-no')
  expect(api.split(' yes no ').join('-'), 'yes-no')
  console.log('#split tests passed')

  expect(api.compact(''), '')
  expect(api.compact('    '), '')
  expect(api.compact('  yes  no  maybe  '), 'yes no maybe')
  expect(api.compact('\n yes \r no \t maybe \n\r\t'), 'yes no maybe')
  console.log('#compact tests passed')

  expect(api.has('', ''), false)
  expect(api.has('', ' '), false)
  expect(api.has(' ', ' '), false)
  expect(api.has('yes no', ''), false)
  expect(api.has('yes no', ' '), false)
  expect(api.has('yes no', 'no'), true)
  expect(api.has('yes no', 'yes'), true)
  expect(api.has('yes no', 'maybe'), false)
  expect(api.has('  yes   no  ', 'yes'), true)
  console.log('#has tests passed')

  expect(api.slice(''), '')
  expect(api.slice('', 5), '')
  expect(api.slice('', -1), '')
  expect(api.slice('zed one two', 0), 'zed one two')
  expect(api.slice('zed one two', -2), 'one two')
  expect(api.slice('zed one two', 0, 1), 'zed')
  expect(api.slice('zed one two', 1, 2), 'one')
  expect(api.slice('zed one two', 1, 3), 'one two')
  expect(api.slice('zed one two', 0, -2), 'zed')
  expect(api.slice('zed one two', 0, -1), 'zed one')
  expect(api.slice('zed one two', 1, -1), 'one')
  console.log('#slice tests passed')

  expect(api.pop(''), '')
  expect(api.pop('yes'), 'yes')
  expect(api.pop('yes no'), 'no')
  console.log('#pop tests passed')

  expect(api.concat('', ''), '')
  expect(api.concat('', 'yes'), 'yes')
  expect(api.concat('yes no', 'maybe'), 'yes no maybe')
  expect(api.concat('yes no', 'maybe so'), 'yes no maybe so')
  expect(api.concat('yes no', 'yes'), 'yes no yes')
  expect(api.concat('  yes  no  ', '  maybe  so '), 'yes no maybe so')
  expect(api.concat('  yes  no  ', 'yes'), 'yes no yes')
  console.log('#concat tests passed')

  expect(api.uniq(''), '')
  expect(api.uniq('yes no yes'), 'yes no')
  expect(api.uniq('yes no yes yes no no yes'), 'yes no')
  expect(api.uniq('yes no Yes'), 'yes no Yes')
  console.log('#uniq tests passed')

  expect(api.push('', ''), '')
  expect(api.push('', 'yes'), 'yes')
  expect(api.push('yes no', 'maybe'), 'yes no maybe')
  expect(api.push('yes no', 'yes'), 'yes no yes')
  expect(api.push('  yes  no  ', 'maybe'), 'yes no maybe')
  expect(api.push('  yes  no  ', 'yes'), 'yes no yes')
  console.log('#push tests passed')

  expect(api.add('yes no', 'yes'), 'yes no')
  expect(api.add('yes no', 'maybe'), 'yes no maybe')
  expect(api.add('  yes   no  ', 'yes'), 'yes no')
  expect(api.add('  yes  no  ', 'maybe'), 'yes no maybe')
  console.log('#add tests passed')

  expect(api.remove('', 'yes'), '')
  expect(api.remove('yes no maybe', 'maybe'), 'yes no')
  expect(api.remove('yes no maybe', 'yes'), 'no maybe')
  expect(api.remove('yes no maybe', 'no'), 'yes maybe')
  expect(api.remove('yes no maybe no', 'no'), 'yes maybe')
  expect(api.remove('yes no no maybe', 'no'), 'yes maybe')
  expect(api.remove('  yes  no  maybe  ', 'maybe'), 'yes no')
  expect(api.remove('  yes  no  maybe  ', 'yes'), 'no maybe')
  expect(api.remove('  yes  no  maybe  ', 'no'), 'yes maybe')
  expect(api.remove('  yes  no  maybe no', 'no'), 'yes maybe')
  expect(api.remove('  yes  no  no maybe', 'no'), 'yes maybe')
  console.log('#remove tests passed')

  console.log('All tests passed =)')
}(require('./'));
